
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels: 
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: kopplin/hello-go:latest

# kubectl apply -f k8s/deployment.yaml